/**
 * MyFitness — Proforma Invoice Search (Google Apps Script)
 *
 * Read-only lookup: given a Sales Order Number, finds the matching invoice
 * PDF in one designated Google Drive folder and returns a viewable/
 * downloadable link. The invoice PDF itself is created and saved into that
 * folder separately, outside this app — this script never creates, writes,
 * or deletes anything. It only reads the folder and (only for a file it
 * actually finds) makes that one file link-viewable so the ASM's browser
 * can open it without being signed into any particular Google account.
 *
 * Matching convention: the invoice for Order Number "SO-2026-00125" must be
 * saved as "SO-2026-00125.pdf" in the configured folder. Matched
 * case-insensitively (and trimmed), so "so-2026-00125.PDF" still matches —
 * useful since the file is named by hand, not generated by this app.
 *
 * Deployed as its own, separate Web App — same reasoning as every other
 * integration in this project (order logging, inventory sync, image scan):
 * one broken/misconfigured deployment should never take another down with
 * it.
 *
 * SETUP:
 *   1. Fill in CONFIG.INVOICE_FOLDER_ID below — the Drive folder where
 *      Proforma Invoice PDFs are saved (see INVOICE_SEARCH_SETUP_GUIDE.md
 *      for how to find a folder's ID from its URL).
 *   2. Deploy > New deployment > Web app. Execute as: Me. Who has access:
 *      Anyone.
 *   3. Copy the "/exec" URL into index.html's INVOICE_SEARCH_WEBAPP_URL
 *      constant. The Invoice topbar button stays hidden until that's done.
 */

var CONFIG = {
  INVOICE_FOLDER_ID: ''
};

// ============================================================================
// ENTRY POINTS
// ============================================================================
function doPost(e){
  return handleSearch(e);
}
function doGet(e){
  return handleSearch(e);
}

function handleSearch(e){
  var orderNo = readOrderNo(e);
  var result = { found: false, orderNo: orderNo };

  if(!orderNo){
    result.error = 'No Order Number given';
    return jsonOut(result);
  }
  if(!CONFIG.INVOICE_FOLDER_ID){
    result.error = "Invoice Search isn't configured yet — INVOICE_FOLDER_ID is blank in InvoiceSearch.gs.";
    return jsonOut(result);
  }

  try{
    var match = findInvoiceFile(CONFIG.INVOICE_FOLDER_ID, orderNo);
    if(!match){
      return jsonOut(result); // found:false — a normal "not uploaded yet" outcome, not an error
    }

    makeViewableWithLink(match);

    result.found = true;
    result.fileName = match.getName();
    result.fileId = match.getId();
    result.viewUrl = 'https://drive.google.com/file/d/' + match.getId() + '/view';
    result.downloadUrl = 'https://drive.google.com/uc?export=download&id=' + match.getId();
    result.sizeBytes = match.getSize();
    result.lastUpdated = match.getLastUpdated();
    return jsonOut(result);

  } catch(err){
    // A wrong/inaccessible INVOICE_FOLDER_ID lands here (DriveApp throws
    // "not found" for both a bad ID and one this account can't see) — the
    // message is surfaced as-is since it's the fastest way to tell which
    // of the two it is while setting this up.
    result.error = String(err && err.message ? err.message : err);
    return jsonOut(result);
  }
}

function readOrderNo(e){
  try{
    if(e && e.postData && e.postData.contents){
      var body = JSON.parse(e.postData.contents);
      return String(body.orderNo || '').trim();
    }
  } catch(err){ /* not JSON — fall through to query param below */ }
  if(e && e.parameter && e.parameter.orderNo) return String(e.parameter.orderNo).trim();
  return '';
}

// ============================================================================
// DRIVE LOOKUP
// ============================================================================

// Exact-match on file name (minus ".pdf", case-insensitive) rather than
// DriveApp.getFilesByName() — that method matches case-sensitively, and the
// file is named by hand, so tolerating a case mismatch matters more here
// than it would for a machine-generated name. If more than one file
// somehow shares the same name (Drive allows duplicate names in one
// folder), the most recently modified one wins — a sane default for what
// should be a rare mistake, not something worth failing the search over.
function findInvoiceFile(folderId, orderNo){
  var folder = DriveApp.getFolderById(folderId);
  var wanted = orderNo.toLowerCase();
  var files = folder.getFiles();
  var match = null;
  while(files.hasNext()){
    var f = files.next();
    var name = f.getName();
    if(!/\.pdf$/i.test(name)) continue;
    var stem = name.replace(/\.pdf$/i, '').trim().toLowerCase();
    if(stem !== wanted) continue;
    if(!match || f.getLastUpdated() > match.getLastUpdated()) match = f;
  }
  return match;
}

// Makes just this one matched file open without sign-in. Tries "Anyone with
// the link" first; if this Workspace domain has external sharing locked
// down (setSharing throws), falls back to "Anyone within the domain" so it
// still works for any signed-in mensabrands.com viewer. If both are
// disabled by domain policy, the link is still returned — the ASM's browser
// will show Drive's own "Request Access" screen, which at least confirms
// the file was found, and IT can adjust the sharing policy or the specific
// folder's permissions from there.
function makeViewableWithLink(file){
  try{
    file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
  } catch(err){
    try{
      file.setSharing(DriveApp.Access.DOMAIN_WITH_LINK, DriveApp.Permission.VIEW);
    } catch(err2){ /* sharing locked down entirely — link still returned as-is */ }
  }
}

function jsonOut(obj){
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}
