/**
 * MyFitness — Proforma Invoice Search (Google Apps Script)
 *
 * Read-only lookup: given a search query, finds matching orders by Order
 * Number, Customer Name (partial match), or Date, cross-referencing the
 * Order History sheet — and for each matching order, checks whether an
 * invoice PDF exists for it in one designated Google Drive folder,
 * returning a viewable/downloadable link when it does.
 *
 * The invoice PDF itself is created and saved into that Drive folder
 * separately, outside this app — this script never creates, writes, or
 * deletes anything. It only reads the Order History sheet and the Drive
 * folder, and (only for a file it actually returns to the caller) makes
 * that one file link-viewable so the ASM's browser can open it without
 * being signed into any particular Google account.
 *
 * Matching convention: the invoice for Order Number "SO-2026-00125" must be
 * saved as "SO-2026-00125.pdf" in the configured folder. Matched
 * case-insensitively (and trimmed), so "so-2026-00125.PDF" still matches —
 * useful since the file is named by hand, not generated by this app.
 *
 * A single query is tried three ways at once, and every order that matches
 * any of them is returned (deduplicated by Order Number):
 *   1. Exact Order Number match (works even for an order not yet logged in
 *      the Order History sheet, as long as its invoice file exists).
 *   2. Date match — accepts "2026-09-08" (ISO), "08-09-2026" / "08/09/2026"
 *      (DD-MM-YYYY), or "08-Sep-2026" (matching the sheet's own Date
 *      column format exactly).
 *   3. Customer Name substring match (case-insensitive).
 *
 * Deployed as its own, separate Web App — same reasoning as every other
 * integration in this project (order logging, inventory sync, image scan):
 * one broken/misconfigured deployment should never take another down with
 * it.
 *
 * SETUP:
 *   1. Fill in CONFIG.INVOICE_FOLDER_ID below — the Drive folder where
 *      Proforma Invoice PDFs are saved (see INVOICE_SEARCH_SETUP_GUIDE.md
 *      for how to find a folder's ID from its URL).
 *   2. Fill in CONFIG.ORDER_HISTORY_SPREADSHEET_ID — the same spreadsheet
 *      the order-logging Web App (apps-script's "order history" project)
 *      writes to. Find it by opening that spreadsheet and copying the ID
 *      out of its URL (.../spreadsheets/d/THIS_PART/edit).
 *   3. Deploy > New deployment (first time) or Manage deployments > New
 *      version (if updating an existing deployment). Web app. Execute as:
 *      Me. Who has access: Anyone.
 *   4. Copy the "/exec" URL into index.html's INVOICE_SEARCH_WEBAPP_URL
 *      constant (only needed the first time — a "new version" of an
 *      existing deployment keeps the same URL).
 */

var CONFIG = {
  INVOICE_FOLDER_ID: '1I-yMA2hPg2NrNufwShzecbUOmSAJlCGl',
  ORDER_HISTORY_SPREADSHEET_ID: '1tOIzq7AWTyXI4TD2tYsIryho4KReo3IM0a7Te9t2t68',
  ORDER_HISTORY_SHEET_NAME: 'Order History'
};

// ============================================================================
// ENTRY POINTS
// ============================================================================
function doPost(e){
  return handleSearch(e);
}
function doGet(e){
  return handleSearch(e);
}

function handleSearch(e){
  var query = readQuery(e);
  if(!query){
    return jsonOut({ error: 'No search text given', query: query, results: [] });
  }

  try{
    var sheetRows = loadOrderHistoryRows();
    var folderIndex = buildInvoiceFolderIndex(CONFIG.INVOICE_FOLDER_ID);
    var matched = {}; // Order No -> {orderNo, customerName, dateFmt}
    var qLower = query.toLowerCase();

    // 1. Exact Order Number match — checked against the sheet AND, failing
    // that, directly against the Drive folder, so an order not yet logged
    // in Order History (e.g. submitted before the sheet-sync fix) can still
    // surface its invoice if one was uploaded for it.
    var directRow = findByOrderNo(sheetRows, query);
    if(directRow){
      matched[directRow.orderNo] = directRow;
    } else if(folderIndex[qLower]){
      matched[query] = { orderNo: query, customerName: '', dateFmt: '' };
    }

    // 2. Date match.
    var parsedDate = tryParseDateQuery(query);
    if(parsedDate){
      sheetRows.forEach(function(r){
        if(r.dateFmt === parsedDate) matched[r.orderNo] = r;
      });
    }

    // 3. Customer Name substring match.
    sheetRows.forEach(function(r){
      if(r.customerName.toLowerCase().indexOf(qLower) !== -1) matched[r.orderNo] = r;
    });

    var results = Object.keys(matched).map(function(orderNo){
      var order = matched[orderNo];
      var file = folderIndex[order.orderNo.toLowerCase()];
      var result = {
        orderNo: order.orderNo,
        customerName: order.customerName || '',
        date: order.dateFmt || '',
        invoiceFound: !!file
      };
      if(file){
        makeViewableWithLink(file);
        result.fileName = file.getName();
        result.fileId = file.getId();
        result.viewUrl = 'https://drive.google.com/file/d/' + file.getId() + '/view';
        result.downloadUrl = 'https://drive.google.com/uc?export=download&id=' + file.getId();
        result.sizeBytes = file.getSize();
        result.lastUpdated = file.getLastUpdated();
      }
      return result;
    });

    // Most recent order first — needs a real date to sort on, so anything
    // missing one (the "matched by filename only, not in the sheet" case)
    // sorts to the end rather than breaking the comparison.
    results.sort(function(a, b){
      if(!a.date) return 1;
      if(!b.date) return -1;
      return new Date(b.date) - new Date(a.date);
    });

    return jsonOut({ query: query, results: results });

  } catch(err){
    // A wrong/inaccessible INVOICE_FOLDER_ID or ORDER_HISTORY_SPREADSHEET_ID
    // lands here — the message is surfaced as-is since it's the fastest way
    // to tell which one while setting this up.
    return jsonOut({ error: String(err && err.message ? err.message : err), query: query, results: [] });
  }
}

// 'query' is the current param name; 'orderNo' is accepted too so a client
// still sending the original single-purpose request shape keeps working.
function readQuery(e){
  try{
    if(e && e.postData && e.postData.contents){
      var body = JSON.parse(e.postData.contents);
      return String(body.query || body.orderNo || '').trim();
    }
  } catch(err){ /* not JSON — fall through to query param below */ }
  if(e && e.parameter){
    return String(e.parameter.query || e.parameter.orderNo || '').trim();
  }
  return '';
}

// ============================================================================
// ORDER HISTORY SHEET
// ============================================================================

// Read-only — never writes back to this sheet (that stays the exclusive job
// of the order-logging Web App). One row per order: {orderNo, customerName,
// dateFmt} — dateFmt is normalized to 'dd-MMM-yyyy' (matching exactly what
// the order-logging script itself writes into the Date column) whether the
// cell holds a real Date value or a plain string, so date-matching below
// only ever has to compare one format against itself.
function loadOrderHistoryRows(){
  var ss = SpreadsheetApp.openById(CONFIG.ORDER_HISTORY_SPREADSHEET_ID);
  var sheet = ss.getSheetByName(CONFIG.ORDER_HISTORY_SHEET_NAME);
  if(!sheet) return [];
  var values = sheet.getDataRange().getValues();
  if(values.length < 2) return [];

  var headers = values[0];
  var orderNoCol = headers.indexOf('Order No');
  var customerCol = headers.indexOf('Customer Name');
  var dateCol = headers.indexOf('Date');
  var tz = Session.getScriptTimeZone();

  var rows = [];
  for(var i = 1; i < values.length; i++){
    var r = values[i];
    var orderNo = String(orderNoCol > -1 ? r[orderNoCol] : '').trim();
    if(!orderNo) continue;
    var dateVal = dateCol > -1 ? r[dateCol] : '';
    var dateFmt = dateVal instanceof Date
      ? Utilities.formatDate(dateVal, tz, 'dd-MMM-yyyy')
      : String(dateVal || '').trim();
    rows.push({
      orderNo: orderNo,
      customerName: String(customerCol > -1 ? r[customerCol] : '').trim(),
      dateFmt: dateFmt
    });
  }
  return rows;
}

function findByOrderNo(rows, orderNo){
  var wanted = orderNo.toLowerCase();
  for(var i = 0; i < rows.length; i++){
    if(rows[i].orderNo.toLowerCase() === wanted) return rows[i];
  }
  return null;
}

// Accepts "2026-09-08" (ISO), "08-09-2026" / "08/09/2026" (DD-MM-YYYY), or
// "08-Sep-2026" (the sheet's own Date column format) — anything else
// returns null (treated as "not a date query", not an error), so a plain
// customer name never gets mistaken for one.
function tryParseDateQuery(q){
  q = q.trim();

  var m = q.match(/^(\d{1,2})-([A-Za-z]{3})-(\d{4})$/);
  if(m){
    var mon = m[2].charAt(0).toUpperCase() + m[2].slice(1, 3).toLowerCase();
    return ('0' + m[1]).slice(-2) + '-' + mon + '-' + m[3];
  }

  m = q.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);
  if(m) return formatDMY(new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3])));

  m = q.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);
  if(m) return formatDMY(new Date(Number(m[3]), Number(m[2]) - 1, Number(m[1])));

  return null;
}
function formatDMY(d){
  if(isNaN(d.getTime())) return null;
  return Utilities.formatDate(d, Session.getScriptTimeZone(), 'dd-MMM-yyyy');
}

// ============================================================================
// DRIVE LOOKUP
// ============================================================================

// One pass over the folder, keyed by file name minus ".pdf" (lowercased) —
// built once per request and reused for every matched order, rather than
// re-scanning the folder per order. If more than one file somehow shares
// the same name (Drive allows duplicate names in one folder), the most
// recently modified one wins — a sane default for what should be a rare
// mistake, not something worth failing the search over.
function buildInvoiceFolderIndex(folderId){
  var index = {};
  var folder = DriveApp.getFolderById(folderId);
  var files = folder.getFiles();
  while(files.hasNext()){
    var f = files.next();
    var name = f.getName();
    if(!/\.pdf$/i.test(name)) continue;
    var stem = name.replace(/\.pdf$/i, '').trim().toLowerCase();
    var existing = index[stem];
    if(!existing || f.getLastUpdated() > existing.getLastUpdated()) index[stem] = f;
  }
  return index;
}

// Makes just this one matched file open without sign-in. Tries "Anyone with
// the link" first; if this Workspace domain has external sharing locked
// down (setSharing throws), falls back to "Anyone within the domain" so it
// still works for any signed-in mensabrands.com viewer. If both are
// disabled by domain policy, the link is still returned — the ASM's browser
// will show Drive's own "Request Access" screen, which at least confirms
// the file was found, and IT can adjust the sharing policy or the specific
// folder's permissions from there.
function makeViewableWithLink(file){
  try{
    file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
  } catch(err){
    try{
      file.setSharing(DriveApp.Access.DOMAIN_WITH_LINK, DriveApp.Permission.VIEW);
    } catch(err2){ /* sharing locked down entirely — link still returned as-is */ }
  }
}

function jsonOut(obj){
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}
